sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install

script:
  - hexo clean
  - hexo generate # generate static files

after_script:
  - cd ./public
  - git init
  - git config user.name "formyown"
  - git config user.email "1119242459@qq.com"
  - git add .
  - git commit -m "Deploy blog pages"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/formyown/formyown.github.io" master:master