sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install

script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  github-token: $GH_TOKEN
  on:
    branches:    
      only:      
        - master 
  local-dir: public